# Generated by Django 5.0.7 on 2024-08-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_project_app', '0003_user_address_user_medical_history_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ManyToManyField(related_name='roles', to='solo_project_app.user'),
        ),
    ]
