# Generated by Django 5.0.7 on 2024-08-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo_project_app', '0005_remove_role_user_role_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
